apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bdikiss-gitops
  namespace: openshift-gitops
  labels:
    app-type: workflow
    app: bdikiss
    rht-gitops.com/janus-argocd: bdikiss-gitops
spec:
  destination:
    namespace: rhdh
    server: https://kubernetes.default.svc
  project: openshift-gitops
  source:
    path: ./kustomize/base
    repoURL: git@github.com:elai-shalev/bdikiss-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
